### ISSUE TITLE
Nginx Error After Sierra Upgrade and upgrade to Docker 17.06

### ISSUE THREAD

**Issue by cstromquist** [chriszarate/docker-wordpress#2]
I just recently upgraded both OSX and Docker and now getting an error when I try to run ```docker-compose up -d``` specifically on the nginx container.

Here is the error I get:
```standard_init_linux.go:187: exec user process caused "exec format error"```

PHPUnit works fine, I just can't get to project.dev now.

Any ideas on how to fix this would be much appreciated.

**Comment by MikeiLL** [comment]
I just upgraded to Sierra and am not getting an error. Haven't upgraded Docker yet. Found this on SO which you may have already come across: https://stackoverflow.com/a/39998089/2223106

Sorry I can't be of more help. Please report back when you solve.

**Comment by cstromquist** [comment]
This one seems to be most relevant: https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error

I'm assuming it's the nginx Dockerfile that's the issue. Do you know where I can find it to edit it?

**Comment by cstromquist** [comment]
I went back to 17.03.1-ce-mac12 and things are working again. Careful if you upgrade Docker!

**Comment by MikeiLL** [comment]
Thanks! I also have 17.03.1-ce.
