### ISSUE TITLE
WORDPRESS_SITE_URL Doesn't seem to work

### ISSUE THREAD

**Issue by bhhaskin** [chriszarate/docker-wordpress#3]
WORDPRESS_SITE_URL doesn't seem to actually work. I see in the docker file you have a hard coded project.dev but no other references to WORDPRESS_SITE_URL.

**Comment by bhhaskin** [comment]
A better example.

Setting `WORDPRESS_SITE_URL` to `http://localhost` currently results in all of wordpress's links point at project.dev

`http://project.dev/wp-content/themes/twentyseventeen/style.css?ver=4.7.2`

the expected result would be that wordpress's links pointed at http://localhost

`http://localhost/wp-content/themes/twentyseventeen/style.css?ver=4.7.2`

I see that you are setting some more stuff in the docker_entrypoint file, but they might not be setting the correct values.

**Comment by MikeiLL** [comment]
Maybe it could be cleared in the Docs. You need to make an `.env` file which contains:

```
DOCKER_DEV_DOMAIN=project.dev
```

or

```
DOCKER_DEV_DOMAIN=help-me.dev
```

or something of the sort. 

You also need to edit your `/etc/hosts` file and add:

```
128.0.0.1   localhost   help-me.dev
```

**Comment by chriszarate** [comment]
@MikeiLL is correct. If you're using [docker-compose-wordpress](https://github.com/chriszarate/docker-compose-wordpress) (which I'd recommend if your goal is a local development environment), edit `.env` to set `DOCKER_DEV_DOMAIN`, which gets passed into `WORDPRESS_SITE_URL` in `docker-compose.yml`.

If you are using plain Docker, the following commands illustrate that `WORDPRESS_SITE_URL` env variable is respected:

```sh
docker run --name mariadb -e MYSQL_DATABASE=wordpress -e MYSQL_ROOT_PASSWORD="" -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mariadb:10.2
docker run --name wordpress --link mariadb:mysql -e WORDPRESS_SITE_URL=http://localhost:8000/ -p 8000:80 -d chriszarate/wordpress:4.8.1
docker exec --user www-data wordpress wp option get siteurl
```

Note that destroying/restarting your wordpress container with different settings has no effect if you do not destroy your mariadb container as well. WordPress is not forcibly reinstalled.
